version: '3.8'

services:
  portfolio-bot:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_BOT_TOKEN=8851269459:AAEpHeyEg2hgg0_TqfjYYbuyb0pGTPRJAG8
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - TELEGRAM_ADMIN_CHAT_ID=${TELEGRAM_ADMIN_CHAT_ID}
      - PORT=8080
